version: "3.4"

services:
  db:
    image: postgres:11.0-alpine
    container_name: postgres-smartstock
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smartstock}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_MAX_CONNECTIONS: 2000
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
  node-modules-front:
  next-frontend: